name: build-dev

on:
  pull_request :
    branches : [ dev ]
  push :
    branches : [ dev ]

jobs:
  build:
    runs-on : ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run : ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: dsTemplate.apk
          path: app/build/outputs/apk/debug/yorozuya-list-dev.apk
