name: Android build & release

on:
  push:
    branches: [ dev ]
  release:
    types: [ published ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execution permissions for Gradlew
        run: |
          chmod +x gradlew

      - name: Build debug and release APKs
        run: ./gradlew assembleDebug assembleRelease

      - name: Upload debug APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload release APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Create release
        id: create_release
        uses: actions/create-release@v3
        with:
          tag_name: ${{ github.event.release.tag_name }}
          release_name: ${{ github.event.release.tag_name }}
          draft: true

      - name: Upload debug APK to release
        if: steps.create_release.outputs.id
        uses: actions/upload-release-artifact@v3
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          asset_name: debug-apk
          artifact_path: "${{ artifacts.debug-apk }}"  # Updated line

      - name: Upload release APK to release
        if: steps.create_release.outputs.id
        uses: actions/upload-release-artifact@v3
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          asset_name: release-apk
          artifact_path: "${{ artifacts.release-apk }}"  # Updated line
